import Head from "next/head";
import Landing from "../components/landing/landing";
import SectionSeparator from "../components/section-separator/section-separator";
import Story from "../components/story/story";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dystopi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <Story />
      <SectionSeparator />
    </div>
  );
}
